language: node_js
node_js:
- '9.11'

cache:
  directories:
    - "node_modules"

script:
  - yarn test
  - yarn build
  - echo my-custom-domain.ru > build/CNAME

deploy:
  provider: pages
  github-token: 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  # Set in the settings page of your repository, as a secure variable
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  target-branch: prod
  on:
    branch: prod